### ISSUE TITLE
Question: silent link failure from TheWorld::instantiate_async

### ISSUE THREAD

**Issue by yowl** [bytecodealliance/wasm-tools#1151]
HI,

I have this wit
```
package foo:foo

interface floats {
  float32-param: func(x: float32)
  float64-param: func(x: float64)
  float32-result: func() -> float32
  float64-result: func() -> float64
}

world the-world {
  import floats
  export floats
}
```
You may recognise it from the tests.  I then have this rust:
```rust
async fn main() -> wasmtime::Result<()> {
    // Configure an `Engine` and compile the `Component` that is being run for
    // the application.
        
    let mut config = Config::new();
    config.wasm_component_model(true);
    config.async_support(true);

    let engine = Engine::new(&config)?;
    // let module = Module::from_file(&engine, "./cswasi.wasm")?;
    let component = Component::from_file(&engine, "C:/github/cs-runtime-example-wasmtime/my-component-cs.wasm")?;
    let mut linker = Linker::new(&engine);

    let state = MyCtx  { };

    let mut table = Table::new();
    let wasi: WasiCtx = WasiCtxBuilder::new().inherit_stdout().set_args(&[""]).build(&mut table)?;

    let customCtx = CustomCtx { state: state, table, wasi };

    wasmtime_wasi::preview2::wasi::command::add_to_linker(&mut linker)?;

    let mut store: Store<CustomCtx> = Store::new(
        &engine,
        customCtx
    );

    TheWorld::add_to_linker(&mut linker, |ctx : &mut CustomCtx| &mut ctx.state)?;

    // let instance = linker.instantiate_async(&mut store, &component.unwrap()).await;
    // let exports  = instance.unwrap().exports(&mut store);


    // let start = (instance.unwrap().get_func(&mut store, "start_test")).expect("export wasnt a function");

    // match start.call(&mut store, &[], &mut []) {
    //     Ok(()) => {}
    //     Err(trap) => {
    //         panic!("execution of foo:foo/floats#float32-param failed {}", trap);
    //     }
    // }

    let (bindings, instance) = TheWorld::instantiate_async(&mut store, &component, &linker).await?;

    match bindings.foo_foo_floats().call_float32_param(store, 2f32).await{
         Ok(()) => {}
        Err(trap) => {
            panic!("execution of foo:foo/floats#float32-param failed {}", trap);
        }       
    }
```
Which fails with
```
thread 'main' panicked at 'execution of foo:foo/floats#float32-param failed error while executing at wasm backtrace:
    0: 0xff31 - <unknown>!undefined_stub
    1: 0xd08823 - <unknown>!cswasi_wit_the_world_ImportsInterop__float32Param
    2: 0x1202fa - cswasi_ExportsImpl__Float32Param
                    at C:\github\cs-wit-bindgen-native-lib\ExportsImpl.cs:8
    3: 0xd0850c - cswasi_wit_the_world_ExportsInterop__wasmExportFloat32Param
                    at C:\github\cs-wit-bindgen-native-lib\testing-csharp\ExportsInterop.cs:19', src\main.rs:108:13
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library\std\src\panicking.rs:578
   1: core::panicking::panic_fmt
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library\core\src\panicking.rs:67
   2: cs_runtime_example::main::async_block$0
             at .\src\main.rs:108
   3: tokio::runtime::park::impl$4::block_on::closure$0<enum2$<cs_runtime_example::main::async_block_env$0> >
             at C:\Users\scott\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.28.1\src\runtime\park.rs:283
   4: tokio::runtime::coop::with_budget
             at C:\Users\scott\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.28.1\src\runtime\coop.rs:107
   5: tokio::runtime::coop::budget
             at C:\Users\scott\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.28.1\src\runtime\coop.rs:73
   6: tokio::runtime::park::CachedParkThread::block_on<enum2$<cs_runtime_example::main::async_block_env$0> >
             at C:\Users\scott\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.28.1\src\runtime\park.rs:283
   7: tokio::runtime::context::BlockingRegionGuard::block_on<enum2$<cs_runtime_example::main::async_block_env$0> >
             at C:\Users\scott\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.28.1\src\runtime\context.rs:315
   8: tokio::runtime::scheduler::multi_thread::MultiThread::block_on<enum2$<cs_runtime_example::main::async_block_env$0> >
             at C:\Users\scott\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.28.1\src\runtime\scheduler\multi_thread\mod.rs:66
   9: tokio::runtime::runtime::Runtime::block_on<enum2$<cs_runtime_example::main::async_block_env$0> >
             at C:\Users\scott\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.28.1\src\runtime\runtime.rs:304
  10: cs_runtime_example::main
             at .\src\main.rs:105
  11: core::ops::function::FnOnce::call_once<enum2$<core::result::Result<tuple$<>,anyhow::Error> > (*)(),tuple$<> >
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca\library\core\src\ops\function.rs:250
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: process didn't exit successfully: `target\debug\cs-runtime-example.exe` (exit code: 101)
```
I believe this is because I have the wrong call name from my webassembly component to the import of the interface method  `float32-param: `  .  It would be nice if this failed at link instantiation time or at `wasm-tools component new`, or something that told me what the name should be that I should be calling from my wasm component.  Maybe you can point me somewhere where I could add some logging/debug so that I can see the unresolved calls?

THanks

**Comment by pchickey** [comment]
I'm not sure what is going on here, but I suspect `undefined_stub` is created in your binary by `lld`: https://github.com/llvm/llvm-project/blob/main/lld/wasm/SymbolTable.cpp#L906 , so you may want to start investigating there

**Comment by yowl** [comment]
Thanks, I made a mistake with the symbol creation in wasm and didn't export it properly.  Having fixed that it now works.  Thanks for the help.
